export type SeoLandingPage = {
  slug: string;
  title: string;
  description: string;
  keyword: string;
  audience: string;
  hero: string;
  proof: string[];
  sections: Array<{ heading: string; body: string }>;
  cta: string;
};

export const seoLandingPages: SeoLandingPage[] = [
  {
    slug: "demo-trading-platform",
    title: "Demo Trading Platform",
    description: "Practice market research, watchlists, charts, and simulated orders in Beyvra before using real capital anywhere.",
    keyword: "demo trading platform",
    audience: "new traders building repeatable habits",
    hero: "A calm demo workspace for learning how markets move without putting money at risk.",
    proof: ["Virtual funds only", "Trading eligibility gates", "Same-origin account security"],
    sections: [
      { heading: "Practice Before Pressure", body: "Beyvra keeps the first experience focused on observation, simulated execution, and review. Users can explore prices, news, and portfolio movement before making any real-world financial decision." },
      { heading: "Built For Clear Risk Thinking", body: "The demo workflow highlights account readiness, watchlists, and risk controls so users understand what a trade would mean before they press an order button." },
    ],
    cta: "Start demo account",
  },
  {
    slug: "paper-trading-app",
    title: "Paper Trading App",
    description: "Use Beyvra as a paper trading app for crypto, stocks, indices, forex education, commodities, and portfolio practice.",
    keyword: "paper trading app",
    audience: "self-directed learners comparing market ideas",
    hero: "Paper trading that separates practice from promises.",
    proof: ["No live order routing", "Simulated balances", "Transparent demo disclosure"],
    sections: [
      { heading: "Simulated By Design", body: "The workspace is intentionally marked as practice. Demo balances, order previews, and account status messaging are separated from real-money flows." },
      { heading: "Review What Changed", body: "Users can track positions, price movement, and portfolio summaries to build a habit of reviewing decisions instead of chasing noise." },
    ],
    cta: "Open paper workspace",
  },
  {
    slug: "crypto-demo-trading",
    title: "Crypto Demo Trading",
    description: "Explore crypto market data, watchlists, candles, and simulated crypto trading workflows in Beyvra.",
    keyword: "crypto demo trading",
    audience: "crypto-curious traders who want structure",
    hero: "Crypto practice without wallet deposits or live exchange routing.",
    proof: ["Crypto watchlists", "Quote and candle workflows", "Demo-only execution"],
    sections: [
      { heading: "Read The Market First", body: "Beyvra helps users follow symbols, compare moves, and study candles before placing any simulated order." },
      { heading: "Keep Risk Visible", body: "Crypto can move quickly. The demo environment keeps educational risk language close to the trading surface." },
    ],
    cta: "Practice crypto demo",
  },
  {
    slug: "forex-demo-account",
    title: "Forex Demo Account",
    description: "Learn forex concepts with demo workflows, calculators, and practice-oriented market pages from Beyvra.",
    keyword: "forex demo account",
    audience: "users learning currency-pair mechanics",
    hero: "A forex learning path focused on calculation, context, and restraint.",
    proof: ["Forex calculators", "Practice workflows", "Clear risk text"],
    sections: [
      { heading: "Understand The Inputs", body: "Use calculators and structured examples to understand position size, entry, exit, and possible loss before experimenting with a simulated trade." },
      { heading: "No Shortcut Language", body: "Beyvra avoids guaranteed-profit claims and keeps forex education grounded in risk, uncertainty, and practice." },
    ],
    cta: "Explore forex practice",
  },
  {
    slug: "stock-market-simulator",
    title: "Stock Market Simulator",
    description: "Build watchlists and practice stock-market research in a simulator-style Beyvra workspace.",
    keyword: "stock market simulator",
    audience: "long-term learners and active market watchers",
    hero: "A stock-market simulator for testing ideas before they become habits.",
    proof: ["Watchlist workflow", "Portfolio view", "Simulated account state"],
    sections: [
      { heading: "Watch Before You Trade", body: "Create a research habit by following symbols, checking market context, and reviewing portfolio effects in a demo setting." },
      { heading: "Better Than Guessing", body: "The simulator turns interest into a repeatable workflow: observe, plan, preview, simulate, and review." },
    ],
    cta: "Build a stock watchlist",
  },
  {
    slug: "indices-demo-trading",
    title: "Indices Demo Trading",
    description: "Practice researching major index movements and simulated index trading in Beyvra.",
    keyword: "indices demo trading",
    audience: "users who follow broad market direction",
    hero: "Study broad-market moves with a practice-first workflow.",
    proof: ["Index market pages", "Risk workflow", "Portfolio context"],
    sections: [
      { heading: "Follow Market Breadth", body: "Index practice helps users think about broader conditions instead of focusing only on one instrument." },
      { heading: "Keep Decisions Bounded", body: "Beyvra's demo approach encourages measured scenario testing and review." },
    ],
    cta: "Explore index practice",
  },
  {
    slug: "commodities-demo-trading",
    title: "Commodities Demo Trading",
    description: "Use Beyvra to learn commodities market behavior with demo tools and risk-aware educational content.",
    keyword: "commodities demo trading",
    audience: "commodity-market learners",
    hero: "Practice commodities research with context, calculators, and visible risk controls.",
    proof: ["Commodity pages", "Profit calculator", "Demo disclosure"],
    sections: [
      { heading: "Connect Price To Context", body: "Commodities react to supply, demand, currency, and macro conditions. Beyvra keeps those ideas close to the workflow." },
      { heading: "Practice Sizing", body: "Use calculator-style tools and order previews to understand how position size changes possible outcomes." },
    ],
    cta: "Practice commodities",
  },
  {
    slug: "trading-charts",
    title: "Trading Charts",
    description: "Explore chart-centered market research in Beyvra with a practice workspace for watchlists and simulated trades.",
    keyword: "trading charts",
    audience: "visual market researchers",
    hero: "Charts for learning, planning, and reviewing market ideas.",
    proof: ["Candle workflows", "Market snapshots", "Research-first UI"],
    sections: [
      { heading: "Make Charts Useful", body: "Charts are most useful when they support a plan. Beyvra pairs chart exploration with portfolio and risk context." },
      { heading: "Review, Do Not Chase", body: "The demo workflow gives users room to compare scenarios and revisit outcomes." },
    ],
    cta: "Open chart workspace",
  },
  {
    slug: "trading-watchlists",
    title: "Trading Watchlists",
    description: "Organize market ideas with Beyvra watchlists before moving into simulated trading workflows.",
    keyword: "trading watchlists",
    audience: "organized market learners",
    hero: "A simple way to turn scattered symbols into a focused routine.",
    proof: ["Personal watchlists", "Instrument lookup", "Portfolio context"],
    sections: [
      { heading: "Group Ideas", body: "Watchlists help users separate research themes, compare assets, and avoid jumping between unrelated markets." },
      { heading: "Act With Context", body: "A better watchlist is connected to charts, news, portfolio review, and eligibility state." },
    ],
    cta: "Create a watchlist",
  },
  {
    slug: "market-news-workspace",
    title: "Market News Workspace",
    description: "Follow market news and economic-calendar context from a Beyvra workspace built for trading education.",
    keyword: "market news workspace",
    audience: "users who combine news with technical context",
    hero: "Market context without pretending headlines are signals.",
    proof: ["News pages", "Economic calendar", "Risk disclosure"],
    sections: [
      { heading: "Context Is Not Certainty", body: "News can explain movement, but it does not remove risk. Beyvra keeps market context educational and clearly separated from advice." },
      { heading: "Plan Around Events", body: "Economic-calendar awareness helps users understand why volatility may change before, during, and after events." },
    ],
    cta: "Read market context",
  },
  {
    slug: "portfolio-analytics-demo",
    title: "Portfolio Analytics Demo",
    description: "Practice reading portfolio exposure, positions, performance, and risk summaries inside Beyvra.",
    keyword: "portfolio analytics demo",
    audience: "users learning portfolio review",
    hero: "A demo portfolio view for understanding exposure before chasing returns.",
    proof: ["Position summaries", "Exposure view", "Risk indicators"],
    sections: [
      { heading: "See The Whole Account", body: "Single trades can feel isolated. Portfolio analytics helps users understand concentration, exposure, and trade impact." },
      { heading: "Review Outcomes", body: "Beyvra encourages post-trade review as part of the practice loop." },
    ],
    cta: "Review demo portfolio",
  },
  {
    slug: "trading-risk-controls",
    title: "Trading Risk Controls",
    description: "Learn how Beyvra presents risk gates, eligibility checks, and simulated account controls before trading workflows.",
    keyword: "trading risk controls",
    audience: "users who care about safer practice habits",
    hero: "Risk controls that are visible before the action happens.",
    proof: ["Eligibility checks", "Demo-only state", "Account protection"],
    sections: [
      { heading: "Controls Before Clicks", body: "The trading workflow checks account and compliance state before simulated activity, keeping users aware of readiness." },
      { heading: "Risk Is Part Of The Product", body: "Beyvra treats risk language, disclosures, and workflow friction as part of the user experience." },
    ],
    cta: "See risk workflow",
  },
  {
    slug: "trading-education-basics",
    title: "Trading Education Basics",
    description: "Start learning trading basics with Beyvra's demo-first approach to markets, charts, and portfolio review.",
    keyword: "trading education basics",
    audience: "beginners who need practical structure",
    hero: "Trading basics taught through a working demo routine.",
    proof: ["Beginner-friendly pages", "No deposit required", "Practice account"],
    sections: [
      { heading: "Start With Process", body: "Good trading education begins with vocabulary, observation, planning, and review." },
      { heading: "Practice Slowly", body: "The demo environment lets users repeat the flow until the mechanics feel familiar." },
    ],
    cta: "Start learning",
  },
  {
    slug: "technical-analysis-practice",
    title: "Technical Analysis Practice",
    description: "Use Beyvra to practice technical-analysis routines in a demo market workspace.",
    keyword: "technical analysis practice",
    audience: "chart learners and strategy testers",
    hero: "A practice surface for reading price behavior with discipline.",
    proof: ["Charts", "Watchlists", "Trade review"],
    sections: [
      { heading: "Patterns Need Context", body: "Technical analysis is more useful when paired with market context, position sizing, and review." },
      { heading: "Test The Routine", body: "Beyvra gives users a place to rehearse a repeatable routine without live execution." },
    ],
    cta: "Practice analysis",
  },
  {
    slug: "risk-management-for-traders",
    title: "Risk Management For Traders",
    description: "Learn risk-management habits for demo trading: sizing, review, exposure, and clear decision rules.",
    keyword: "risk management for traders",
    audience: "users building more disciplined habits",
    hero: "Risk management belongs before the order, not after the loss.",
    proof: ["Exposure awareness", "Account gates", "Review workflow"],
    sections: [
      { heading: "Size Before Direction", body: "Risk management starts with deciding what can go wrong and how much a scenario matters." },
      { heading: "Use Review Loops", body: "Demo trading is strongest when every idea has a reason, result, and review." },
    ],
    cta: "Learn risk workflow",
  },
  {
    slug: "mobile-trading-demo",
    title: "Mobile Trading Demo",
    description: "Explore Beyvra's responsive demo trading workspace across desktop and mobile browsers.",
    keyword: "mobile trading demo",
    audience: "users who check markets across devices",
    hero: "Market practice that works where you are, with the same risk boundaries.",
    proof: ["Responsive UI", "Same-origin auth", "Demo account"],
    sections: [
      { heading: "Consistent Access", body: "Responsive pages help users check watchlists, market context, and account state without switching products." },
      { heading: "Small Screen, Same Caution", body: "Mobile access keeps the same demo disclosure and account controls." },
    ],
    cta: "Try on mobile",
  },
  {
    slug: "secure-trading-login",
    title: "Secure Trading Login",
    description: "Beyvra uses backend-owned session boundaries and Keycloak identity authority for secure account access.",
    keyword: "secure trading login",
    audience: "security-conscious users",
    hero: "A login model designed to keep browser JavaScript away from long-lived tokens.",
    proof: ["HttpOnly cookies", "Keycloak authority", "Same-origin API"],
    sections: [
      { heading: "Backend-Owned Sessions", body: "Beyvra's browser flow is designed around backend-owned cookies and a same-origin API boundary." },
      { heading: "Identity Authority", body: "Registration, email verification, and password reset are owned by the configured identity provider when production identity is enabled." },
    ],
    cta: "Go to sign in",
  },
  {
    slug: "market-data-demo",
    title: "Market Data Demo",
    description: "Follow market data examples, quotes, candles, and snapshots inside Beyvra's demo workspace.",
    keyword: "market data demo",
    audience: "users learning how market feeds support decisions",
    hero: "Market data for practice, research, and better questions.",
    proof: ["Quote workflows", "Candle workflows", "Provider-gated data"],
    sections: [
      { heading: "Know The Source", body: "Data quality matters. Beyvra separates provider-gated market data from presentation so users know what is available." },
      { heading: "Use Data With Care", body: "No feed removes uncertainty. The demo experience treats data as context, not instruction." },
    ],
    cta: "View market data",
  },
  {
    slug: "economic-calendar-trading",
    title: "Economic Calendar Trading",
    description: "Use Beyvra's economic-calendar pages to understand events that can affect market volatility.",
    keyword: "economic calendar trading",
    audience: "macro-aware market learners",
    hero: "Plan practice sessions around events that may change volatility.",
    proof: ["Calendar route", "News context", "Risk disclosure"],
    sections: [
      { heading: "Events Move Attention", body: "Calendar events can shift liquidity and volatility. Beyvra helps users keep those moments visible." },
      { heading: "Practice The Plan", body: "A demo account lets users test how they would behave around scheduled events without real capital." },
    ],
    cta: "Open calendar",
  },
  {
    slug: "trading-simulator-comparison",
    title: "Trading Simulator Comparison",
    description: "Compare what matters in a trading simulator: security, clarity, demo funds, market context, and transparent risk language.",
    keyword: "trading simulator comparison",
    audience: "users evaluating demo trading tools",
    hero: "Choose a simulator by workflow quality, not flashy claims.",
    proof: ["Transparent demo state", "Risk-first pages", "Original educational content"],
    sections: [
      { heading: "What To Compare", body: "Look for clear account state, educational pages, secure login, useful watchlists, and honest risk disclosure." },
      { heading: "Why Beyvra", body: "Beyvra focuses on a complete practice workflow instead of promising outcomes." },
    ],
    cta: "Compare with demo",
  },
  {
    slug: "client-market-workspace",
    title: "Client Market Workspace",
    description: "Beyvra gives clients a clean market workspace for watchlists, demo portfolios, market context, and account readiness.",
    keyword: "client market workspace",
    audience: "clients who want a structured market dashboard",
    hero: "A market workspace that makes the next responsible action clear.",
    proof: ["Client portal", "Account readiness", "Interactive inquiry form"],
    sections: [
      { heading: "One Place To Start", body: "The public site routes users into a clear client portal with demo trading, profile, security, and market sections." },
      { heading: "Track Real Interest", body: "Consent-aware tracking and a clean webform help Beyvra understand which pages are useful without hiding what is collected." },
    ],
    cta: "Request access",
  },
];

export const seoPageBySlug = new Map(seoLandingPages.map((page) => [page.slug, page]));
