export const times = [
  {
    value: "CRV/USD",
    name: "Quickler",
    profit: "85",
    image: "/menu-images/timezones/timezone-1.png",
    quickTrading: false,
    inProfit: true,
  },
  {
    value: "AAVE/USD",
    name: "Asia Composite Index",
    profit: "85",
    image: "/menu-images/timezones/timezone-2.png",
    inProfit: true,
  },
  {
    value: "AVAX/USD",
    name: "Bras Index",
    profit: "85",
    image: "/menu-images/timezones/timezone-3.png",
    inProfit: true,
  },
  {
    value: "BAT/USD",
    name: "Cafeina Index",
    profit: "85",
    image: "/menu-images/timezones/timezone-4.png",
    inProfit: true,
  },
  {
    value: "BCH/USD",
    name: "Commodity Composite Index",
    profit: "85",
    image: "/menu-images/timezones/timezone-5.png",
    inProfit: true,
  },
  {
    value: "BTC/USD",
    name: "Europe Composite Index",
    profit: "85",
    image: "/menu-images/timezones/timezone-6.png",
    inProfit: true,
  },
  {
    value: "CRV/USD",
    name: "LATAM Index",
    profit: "82",
    image: "/menu-images/timezones/timezone-7.png",
    inProfit: true,
  },
  {
    value: "USDT/USD",
    name: "EUR/USD",
    profit: "80",
    image: "/menu-images/timezones/timezone-8.png",
  },
  {
    value: "ETH/USD",
    name: "GBP/USD",
    profit: "80",
    image: "/menu-images/timezones/timezone-9.png",
  },
];

export const forex = [
  {
    value: "CRV/USD",
    name: "Asia Composite Index",
    profit: "-0.06",
    image: "/menu-images/timezones/timezone-2.png",
  },
  {
    value: "AAVE/USD",
    name: "Bras Index",
    profit: "+0.07",
    image: "/menu-images/timezones/timezone-3.png",
    inProfit: true,
  },
  {
    value: "AVAX/USD",
    name: "Cafeina Index",
    profit: "+0.26",
    image: "/menu-images/timezones/timezone-4.png",
    inProfit: true,
  },
  {
    value: "BAT/USD",
    name: "Commodity Composite Index",
    profit: "+0.01",
    image: "/menu-images/timezones/timezone-5.png",
    inProfit: true,
  },
  {
    value: "BCH/USD",
    name: "Europe Composite Index",
    profit: "-3.52",
    image: "/menu-images/timezones/timezone-6.png",
  },
  {
    value: "BTC/USD",
    name: "LATAM Index",
    profit: "+0.21",
    image: "/menu-images/timezones/timezone-7.png",
    inProfit: true,
  },
  {
    value: "CRV/USD",
    name: "EUR/USD",
    profit: "-2.12",
    image: "/menu-images/timezones/timezone-8.png",
    inProfit: true,
  },
  {
    value: "USDT/USD",
    name: "GBP/USD",
    profit: "+3.04",
    image: "/menu-images/timezones/timezone-9.png",
  },
  {
    value: "ETH/USD",
    name: "Quickler",
    profit: "-0.86",
    image: "/menu-images/timezones/timezone-1.png",
  },
];

export const stocks = [
  {
    value: "CRV/USD",
    name: "BMV",
    profit: "€92.97",
    image: "/menu-images/stocks/stock1.png",
  },
  {
    value: "AAVE/USD",
    name: "3M Company",
    profit: "",
    image: "/menu-images/stocks/stock2.png",
  },
  {
    value: "AVAX/USD",
    name: "Alibaba",
    profit: "",
    image: "/menu-images/stocks/stock3.png",
  },
  {
    value: "BAT/USD",
    name: "Amazon",
    profit: "",
    image: "/menu-images/stocks/stock4.png",
  },
  {
    value: "BCH/USD",
    name: "AMD",
    profit: "",
    image: "/menu-images/stocks/stock5.png",
  },
  {
    value: "BTC/USD",
    name: "Apple",
    profit: "",
    image: "/menu-images/stocks/stock6.png",
  },
  {
    value: "CRV/USD",
    name: "Baidu",
    profit: "",
    image: "/menu-images/stocks/stock7.png",
  },
  {
    value: "USDT/USD",
    name: "Boeing",
    profit: "",
    image: "/menu-images/stocks/stock8.png",
  },
];
