export type CurrentDrawerType =
  | "trades"
  | "market"
  | "events"
  | "help"
  | "assets"
  | "ai"
  | "news"
  | null;

export type LeftSubDrawer =
  | "help-center"
  | "support"
  | "trading-platform"
  | "education-menu"
  | "trading-tutorials"
  | "event-join-leagues"
  | "events-signals-club"
  | "what-is-trading" 
  | "why-coose-us"
  | "barcode"
  | "published-strategies"
  | "ai-asset-summary"
  | "forex-market-sub"
  | "astro-market-submenu"
  | "crypto-market-submenu"
  | "trading-conditions-market-submenu"
  | "signals-market-submenu"
  | "custom-strategies-market-submenu"
  | "strategies-market-submenu"
  | "indicators-market-submenu"
  | "themes-market-submenu"
  | "advisers-market-submenu"
  | null;

  export type RightDrawerContent =
    | "account"
    | "payments"
    | "profile"
    | "verification"
    | "verify-payment"
    | null;

  export type RightSubDrawerContent =
    | "settings"
    | "status"
    | "twofactor"
    | "personalSettings"
    | "verification"
    | "appearance"
    | "transfer"
    | "trading"
    | "notifications"
    | "barcode"
    | "user-notifications"
    | "change-password"
    | "edit-name"
    | "confirm-email"
    | "confirm-phone"
    | "select-account"
    | "withdraw"
    | "add-account"
    | "traders-way"
    | "invite-friends"
    | "verify-payment"
    | "mega-box-rewards"
    | "payments-deposit"
    | "select-deposit-amount"
    | "payment-method"
    | "card-details-menu"
    | "payments-promo-code"
    | "select-withdraw-account"
    | "boost-cubes"
    | "referral-program"
    | "depoist-successful"
    | "transfer-successful"
    | "promo-code-applied"
    | "verification-helpcenter-menu"
    | "get-rewards-deposit"
    | "verification-helpcenter-sub-menu"
    | "password-success"
    | "account-archive-menu"
    | "account-archive-success-menu"
    | "add-account-name"
    | "account-rename"
    | "select-withdarw-request"
    | "withdraw-payment"
    | "crypto-payment"
    | "crypto-payment-processing"
    | "deposit-confirm-payment"
    | "wire-transfer"
    | null;


    export type WindowDrawer = "portfolio" | null