export const ForexMarketSubMenuList = [
  {
    id: 1,
    title: "Duet +1",
    rating: "5.0",
    price: "8.00",
    total: "173,125 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Duet.svg",
  },
  {
    id: 2,
    title: "2D",
    rating: "5.0",
    price: "23.00",
    total: "29,960 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/2D.svg",
  },
  {
    id: 3,
    title: "U Turn",
    rating: "4.3",
    price: "22.00",
    total: "13,883 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/UTurn.svg",
  },
  {
    id: 4,
    title: "Ichimoku Lines",
    rating: "4.3",
    price: "15.00",
    total: "11,363 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Lines.svg",
  },
  {
    id: 5,
    title: "Trend Hunter",
    rating: "4.1",
    price: "30.00",
    total: "22,075 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/TrendHunter.svg",
  },
  {
    id: 6,
    title: "MACD Power",
    rating: "4.0",
    price: "20.00",
    total: "17,035 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MACDPower.svg",
  },
];
export const CryptoMarketSubMenuList = [
  {
    id: 1,
    title: "One Minute",
    rating: "5.0",
    price: "1.00",
    total: "5,385 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OneMinute.svg",
  },
  {
    id: 2,
    title: "Find Direction",
    rating: "5.0",
    price: "1.00",
    total: "3,593 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/FindDirection.svg",
  },
  {
    id: 3,
    title: "Double Crossover",
    rating: "5.0",
    price: "1.00",
    total: "2,467 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/DoubleCrossover.svg",
  },
  {
    id: 4,
    title: "Crypto Swing",
    rating: "5.0",
    price: "6.00",
    total: "50,175 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoSwing.svg",
  },
  {
    id: 5,
    title: "Crypto Scalping",
    rating: "5.0",
    price: "3.00",
    total: "146,883 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoScalping.svg",
  },
  {
    id: 6,
    title: "Crypto Intraday",
    rating: "5.0",
    price: "5.00",
    total: "131,121 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoIntraday.svg",
  },
  {
    id: 7,
    title: "Cryptonite",
    rating: "5.0",
    price: "1.00",
    total: "148 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Cryptonite.svg",
  },
  {
    id: 8,
    title: "Crypto Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "21,216 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroSwing.svg",
  },
  {
    id: 9,
    title: "Crypto Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "54,909 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroScalping.svg",
  },
  {
    id: 10,
    title: "Crypto Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "122,493 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroIntraday.svg",
  },
];

export const AstroMarketSubMenuList = [
  {
    id: 1,
    title: "OTC Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "11,225 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OneMinute.svg",
  },
  {
    id: 2,
    title: "OTC Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "36,906 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/FindDirection.svg",
  },
  {
    id: 3,
    title: "OTC Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "8,991 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/DoubleCrossover.svg",
  },
  {
    id: 4,
    title: "Minor Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "6,597 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoSwing.svg",
  },
  {
    id: 5,
    title: "Minor Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "35,875 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoScalping.svg",
  },
  {
    id: 6,
    title: "Minor Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "8,555 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoIntraday.svg",
  },
  {
    id: 7,
    title: "Major Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "13,575 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Cryptonite.svg",
  },
  {
    id: 8,
    title: "Major Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "79,499 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroSwing.svg",
  },
  {
    id: 9,
    title: "Major Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "32,722 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroScalping.svg",
  },
];

export const TradingConditionsMarketSubMenuList = [
  {
    id: 1,
    title: "Expert Status",
    rating: "5.0",
    price: "399.00",
    total: "688 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/ExpertStatus.svg",
  },
  {
    id: 2,
    title: "Advanced Status",
    rating: "5.0",
    price: "98.00",
    total: "2,866 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/AdvancedStatus.svg",
  },
  {
    id: 3,
    title: "Up to 93% profitability",
    rating: "5.0",
    price: "350.00",
    total: "365 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/UpTo93Profitability.svg",
  },
  {
    id: 4,
    title: "Up to 89% profitability",
    rating: "5.0",
    price: "70.00",
    total: "983 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/UpTo89Profitability.svg",
  },
];

export const SignalsMarketSubMenuList = [
  {
    id: 1,
    title: "OTC Swing",
    rating: "5.0",
    price: "5.00",
    total: "60,736 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCSwing.svg",
  },
  {
    id: 2,
    title: "OTC Scalping",
    rating: "5.0",
    price: "2.00",
    total: "219,391 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCScalping.svg",
  },
  {
    id: 3,
    title: "OTC Intraday",
    rating: "5.0",
    price: "4.00",
    total: "29,832 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCIntraday.svg",
  },
  {
    id: 4,
    title: "Metals Swing",
    rating: "5.0",
    price: "6.00",
    total: "18,112 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MetalsSwing.svg",
  },
  {
    id: 5,
    title: "Metals Scalping",
    rating: "5.0",
    price: "3.00",
    total: "64,361 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MetalsScalping.svg",
  },
  {
    id: 6,
    title: "Metals Intraday",
    rating: "5.0",
    price: "5.00",
    total: "16,642 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MetalsIntraday.svg",
  },
  {
    id: 7,
    title: "Indices Swing",
    rating: "5.0",
    price: "8.00",
    total: "29,039 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/IndicesSwing.svg",
  },
  {
    id: 8,
    title: "Indices Scalping",
    rating: "5.0",
    price: "8.00",
    total: "29,039 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/IndicesScalping.svg",
  },
  {
    id: 9,
    title: "Crypto Swing",
    rating: "5.0",
    price: "6.00",
    total: "50,241 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoSwing.svg",
  },
  {
    id: 10,
    title: "Crypto Scalping",
    rating: "5.0",
    price: "3.00",
    total: "147,104 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoScalping.svg",
  },
  {
    id: 11,
    title: "Crypto Intraday",
    rating: "5.0",
    price: "5.00",
    total: "131,159 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoIntraday.svg",
  },
  {
    id: 12,
    title: "Commodities Swing",
    rating: "5.0",
    price: "5.00",
    total: "28,889 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CommoditiesSwing.svg",
  },
  {
    id: 13,
    title: "Commodities Scalping",
    rating: "5.0",
    price: "2.00",
    total: "104,894 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CommoditiesScalping.svg",
  },
  {
    id: 14,
    title: "Commodities Scalping",
    rating: "5.0",
    price: "4.00",
    total: "251,246 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CommoditiesScalping2.svg",
  },
  {
    id: 15,
    title: "OTC Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "11,293 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCAstroSwing.svg",
  },
  {
    id: 16,
    title: "OTC Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "37,021 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCAstroScalping.svg",
  },
  {
    id: 17,
    title: "OTC Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "9,021 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OTCAstroIntraday.svg",
  },
  {
    id: 18,
    title: "Minor Astro Swing",
    rating: "5.0",
    price: "2.00",
    total: "9,021 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MinorAstroSwing.svg",
  },
  {
    id: 19,
    title: "Minor Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "36,056 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MinorAstroScalping.svg",
  },
  {
    id: 20,
    title: "Minor Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "8,588 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MinorAstroIntraday.svg",
  },
  {
    id: 21,
    title: "Major Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "13,628 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorAstroSwing.svg",
  },
  {
    id: 22,
    title: "Major Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "79,848 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorAstroScalping.svg",
  },
  {
    id: 23,
    title: "Major Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "32,796 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorAstroIntraday.svg",
  },
  {
    id: 24,
    title: "Crypto Astro Swing",
    rating: "5.0",
    price: "3.00",
    total: "21,233 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroSwing.svg",
  },
  {
    id: 25,
    title: "Crypto Astro Scalping",
    rating: "5.0",
    price: "1.00",
    total: "54,961 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroScalping.svg",
  },
  {
    id: 26,
    title: "Crypto Astro Intraday",
    rating: "5.0",
    price: "2.00",
    total: "122,515 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CryptoAstroIntraday.svg",
  },
  {
    id: 27,
    title: "Major Swing",
    rating: "5.0",
    price: "20.00",
    total: "71,761 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorSwing.svg",
  },
  {
    id: 28,
    title: "Minor Swing",
    rating: "5.0",
    price: "5.00",
    total: "22,115 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MinorSwing.svg",
  },
  {
    id: 29,
    title: "Minor Intraday",
    rating: "5.0",
    price: "10.00",
    total: "58,913 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MinorIntraday.svg",
  },
  {
    id: 30,
    title: "Major Intraday",
    rating: "5.0",
    price: "10.00",
    total: "70,046 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorIntraday.svg",
  },
  {
    id: 31,
    title: "Major Scalping",
    rating: "5.0",
    price: "5.00",
    total: "43,794 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MajorScalping.svg",
  },
];

export const StrategiesMarketSubMenuList = [
  {
    id: 1,
    title: "Triple Rebound",
    rating: "5.0",
    price: "30.00",
    total: "41,591 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/TripleRebound.svg",
  },
  {
    id: 2,
    title: "Trio",
    rating: "5.0",
    price: "8.00",
    total: "26,248 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Trio.svg",
  },
  {
    id: 3,
    title: "One Minute",
    rating: "5.0",
    price: "1.00",
    total: "5,385 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/OneMinute.svg",
  },
  {
    id: 4,
    title: "Kind Martin",
    rating: "5.0",
    price: "4.50",
    total: "20,697 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/KindMartin.svg",
  },
  {
    id: 5,
    title: "Friday",
    rating: "5.0",
    price: "7.00",
    total: "22,058 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Friday.svg",
  },
  {
    id: 6,
    title: "Find Direction",
    rating: "5.0",
    price: "1.00",
    total: "3,593 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/FindDirection.svg",
  },
  {
    id: 7,
    title: "Duet +1",
    rating: "5.0",
    price: "8.00",
    total: "173,125 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Duet.svg",
  },
  {
    id: 8,
    title: "Double Crossover",
    rating: "5.0",
    price: "1.00",
    total: "2,467 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/DoubleCrossover.svg",
  },
  {
    id: 9,
    title: "Jack Tar",
    rating: "4.9",
    price: "15.00",
    total: "10,505 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/JackTar.svg",
  },
  {
    id: 10,
    title: "Safari",
    rating: "4.7",
    price: "10.00",
    total: "11,049 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Safari.svg",
  },
  {
    id: 11,
    title: "Peacock",
    rating: "4.7",
    price: "10.00",
    total: "13,594 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Peacock.svg",
  },
  {
    id: 12,
    title: "Diving",
    rating: "4.7",
    price: "3.00",
    total: "13,594 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Diving.svg",
  },
  {
    id: 13,
    title: "Axel",
    rating: "4.7",
    price: "3.00",
    total: "18,203 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Axel.svg",
  },
  {
    id: 14,
    title: "2D",
    rating: "4.7",
    price: "23.00",
    total: "30,704 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/2D.svg",
  },
  {
    id: 15,
    title: "Quick Turn",
    rating: "4.5",
    price: "11.00",
    total: "6,529 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/QuickTurn.svg",
  },
  {
    id: 16,
    title: "Mountain Stream",
    rating: "4.5",
    price: "25.00",
    total: "15,349 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MountainStream.svg",
  },
  {
    id: 17,
    title: "Horizon",
    rating: "4.5",
    price: "20.00",
    total: "8,513 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Horizon.svg",
  },
  {
    id: 18,
    title: "Expert Strategies",
    rating: "4.5",
    price: "163.00",
    total: "704 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/ExpertStrategies.svg",
  },
  {
    id: 19,
    title: "Advanced Strategies",
    rating: "4.5",
    price: "57.00",
    total: "1,754 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/AdvancedStrategies.svg",
  },
  {
    id: 20,
    title: "U Turn",
    rating: "4.3",
    price: "22.00",
    total: "13,883 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/UTurn.svg",
  },
  {
    id: 21,
    title: "Stripped Clouds",
    rating: "4.3",
    price: "7.00",
    total: "3,922 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/StrippedClouds.svg",
  },
  {
    id: 22,
    title: "Rodeo",
    rating: "4.3",
    price: "25.00",
    total: "7,075 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Rodeo.svg",
  },
  {
    id: 23,
    title: "Ichimoku Lines",
    rating: "4.3",
    price: "15.00",
    total: "11,363 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Lines.svg",
  },
  {
    id: 24,
    title: "Crocodile Dundee",
    rating: "4.3",
    price: "20.00",
    total: "7,312 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/CrocodileDundee.svg",
  },
  {
    id: 25,
    title: "Confrontation",
    rating: "4.2",
    price: "3.00",
    total: "12,064 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Confrontation.svg",
  },
  {
    id: 26,
    title: "Trend Hunter",
    rating: "4.1",
    price: "30.00",
    total: "22,075 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/TrendHunter.svg",
  },
  {
    id: 27,
    title: "Predatory Look",
    rating: "4.1",
    price: "30.00",
    total: "6,244 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/PredatoryLook.svg",
  },
  {
    id: 28,
    title: "MACD Professional",
    rating: "4.1",
    price: "20.00",
    total: "13,050 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MACDProfessional.svg",
  },
  {
    id: 29,
    title: "River Flow",
    rating: "4.0",
    price: "16.00",
    total: "6,151 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/RiverFlow.svg",
  },
  {
    id: 30,
    title: "Perfect Turn",
    rating: "4.0",
    price: "9.00",
    total: "6,228 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/PerfectTurn.svg",
  },
  {
    id: 31,
    title: "Millenium",
    rating: "4.0",
    price: "8.00",
    total: "48,174 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Millenium.svg",
  },
  {
    id: 32,
    title: "MACD Power",
    rating: "4.0",
    price: "20.00",
    total: "17,035 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/MACDPower.svg",
  },
  {
    id: 33,
    title: "Early Start",
    rating: "4.0",
    price: "5.00",
    total: "7,158 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/EarlyStart.svg",
  },
  {
    id: 34,
    title: "Double Bollinger",
    rating: "4.0",
    price: "9.00",
    total: "8,797 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/",
  },
];

export const IndicatorsMarketSubMenuList = [
  {
    id: 1,
    title: "Pivot Points",
    rating: "4.0",
    price: "30.00",
    total: "41,584 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/PivotPoints.svg",
  },
  {
    id: 2,
    title: "Inversion Bollinger",
    rating: "4.0",
    price: "22.00",
    total: "43,010 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/InversionBollinger.svg",
  },
  {
    id: 3,
    title: "Bill Williams’ Fractals",
    rating: "4.0",
    price: "5.00",
    total: "59,786 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/BillWilliamsFractals.svg",
  },
  {
    id: 4,
    title: "Stochastic RSI",
    rating: "3.5",
    price: "6.00",
    total: "25,187 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/StochasticRSI.svg",
  },
];

export const AdvisersMarketSubMenuList = [
  {
    id: 1,
    title: "Sliding on Average Advising",
    rating: "4.5",
    price: "15.00",
    total: "73,731 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/PivotPoints.svg",
  },
  {
    id: 2,
    title: "MACD Adviser",
    rating: "4.5",
    price: "15.00",
    total: "97,855 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/InversionBollinger.svg",
  },
  {
    id: 3,
    title: "Predatory Look Adviser",
    rating: "4.0",
    price: "20.00",
    total: "53,414 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/BillWilliamsFractals.svg",
  },
];

export const ThemesMarketSubMenuList = [
  {
    id: 1,
    title: "Purple Haze",
    rating: "5.0",
    total: "106,689 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/PurpleHaze.svg",
  },
  {
    id: 2,
    title: "Inspire",
    rating: "5.0",
    total: "731 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Inspire.svg",
    price: "1.00",
    month: true,
  },
  {
    id: 3,
    title: "Fresh Berries",
    rating: "5.0",
    total: "6,518 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/FreshBerries.svg",
    price: "1.00",
    month: true,
  },
  {
    id: 4,
    title: "Spring Grass",
    rating: "5.0",
    total: "15,222 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/SpringGrass.svg",
    price: "1.00",
    month: true,
  },
  {
    id: 5,
    title: "Sunny Line",
    rating: "5.0",
    total: "4,081 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/SunnyLine.svg",
    price: "1.00",
    month: true,
  },
  {
    id: 6,
    title: "Flower Mint",
    rating: "5.0",
    total: "2,551 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/FlowerMint.svg",
    price: "1.00",
    month: true,
  },
  {
    id: 7,
    title: "Cryptonite",
    rating: "5.0",
    total: "148 traders purchased",
    img: "/market-menu-images/market-sub-menu-images/Cryptonite.svg",
    price: "1.00",
    month: true,
  },
];

export const CustomStrategiesMarketSubMenuList = [
  {
    id: 1,
    rating: "3.1",
    title: "GhoshStrategy",
    total: "Strategy by Gosh",
    img: "/market-menu-images/market-sub-menu-images/GhostStrategyIcon.svg",
  },
  {
    id: 2,
    rating: "3.0",
    title: "Candle probability",
    total: "Strategy by Mohit singh",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 3,
    rating: "2.8",
    title: "Strategy",
    total: "Strategy by 106926259",
    img: "/market-menu-images/market-sub-menu-images/GhostStrategyIcon.svg",
  },
  {
    id: 4,
    rating: "2.7",
    title: "Ak2",
    total: "Strategy by Ajit Mishra",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 5,
    rating: "2.6",
    title: "Strategy",
    total: "Strategy by 97316105",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 6,
    rating: "2.5",
    title: "Cross",
    total: "Strategy by Sachin Kumar Mahato Mahato",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 7,
    rating: "1.0",
    title: "Up With Blue",
    total: "Strategy by Mostafa Mahmoud",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 8,
    rating: "1.0",
    title: "Strategy 1 min",
    total: "Strategy by Saloni Rai",
    price: "1.00",
    img: "/market-menu-images/market-sub-menu-images/EarthIcon.svg",
  },
  {
    id: 9,
    rating: "0.0",
    title: "WMA Squad",
    total: "Strategy by Tanmoy",
    white: true,
    img: "/market-menu-images/market-sub-menu-images/WMASquad.svg",
  },
  {
    id: 10,
    rating: "0.0",
    title: "Winning Cross",
    total: "Strategy by Alvaro Camilo",
    white: true,
    img: "/market-menu-images/market-sub-menu-images/WinningCross.svg",
  },
  {
    id: 11,
    rating: "0.0",
    title: "Vitor Taki",
    total: "Strategy by Manoel Vitor",
    img: "/market-menu-images/market-sub-menu-images/VitorTaki.svg",
  },
  {
    id: 12,
    rating: "0.0",
    title: "Trend Chasing",
    total: "Strategy by visnu707",
    img: "/market-menu-images/market-sub-menu-images/TrendChasing.svg",
  },
  {
    id: 13,
    rating: "0.0",
    title: "Trend",
    total: "Strategy by Budi buntoro BUNTORO",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 14,
    rating: "0.0",
    title: "TradoMA",
    total: "Strategy by Budi buntoro BUNTORO",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 15,
    rating: "0.0",
    title: "The Right Destanation",
    total: "Strategy by Youssef Amin",
    img: "/market-menu-images/market-sub-menu-images/TheRightDestanation.svg",
  },
  {
    id: 16,
    rating: "0.0",
    title: "Strategy",
    total: "Strategy by Arpit Tyagi",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 17,
    rating: "0.0",
    title: "Strategy",
    total: "Strategy by Rodrigo Farias dos Santos",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 18,
    rating: "0.0",
    title: "Strategy",
    total: "Strategy by Enibemo patton Bishwajit",
    img: "/market-menu-images/market-sub-menu-images/VitorTaki.svg",
  },
  {
    id: 19,
    rating: "0.0",
    title: "Strategy",
    total: "Strategy by Prince Patel",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 20,
    rating: "0.0",
    title: "Strategy",
    total: "Strategy by Ahmed",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 21,
    rating: "0.0",
    title: "Sniper 1 Min",
    total: "Strategy by addnorrax",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 22,
    rating: "0.0",
    title: "SMA5MIN",
    total: "Strategy by Avnish Kumar",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 23,
    rating: "0.0",
    title: "Sea saw",
    total: "Strategy by 110705373",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 24,
    rating: "0.0",
    title: "Rusa",
    total: "Strategy by Josias Drums",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 25,
    rating: "0.0",
    title: "ReylionFX",
    total: "Strategy by John Reymond Oropeza",
    img: "/market-menu-images/market-sub-menu-images/VitorTaki.svg",
  },
  {
    id: 26,
    rating: "0.0",
    title: "pintyabhau strategy",
    total: "Strategy by Kanchan Narkhede",
    img: "/market-menu-images/market-sub-menu-images/GhostStrategyIcon.svg",
  },
  {
    id: 27,
    rating: "0.0",
    title: "PEESS",
    total: "Strategy by EH รอดสุด",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 28,
    rating: "0.0",
    title: "MRE",
    total: "Strategy by dk",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 29,
    rating: "0.0",
    title: "MA Crossover Bot",
    total: "Strategy by Akhil Kumar Kumar",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 30,
    rating: "0.0",
    title: "GT Strategy",
    total: "Strategy by Sakra Pedige Gayan Thushara Gunathilaka Gunathilaka",
    img: "/market-menu-images/market-sub-menu-images/GTStrategy.svg",
  },
  {
    id: 31,
    rating: "0.0",
    title: "G Strategy",
    total: "Strategy by Ghosh",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 32,
    rating: "0.0",
    title: "DrHassan Best Strategy",
    total: "Strategy by Dr.Hassan Al-Shaikh Al-Shaikh",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 33,
    rating: "0.0",
    title: "Dragone strategy",
    total: "Strategy by Nishi Khan Khan",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 34,
    rating: "0.0",
    title: "Double EMA RSI Strategy",
    total: "Strategy by Kaitou",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 35,
    rating: "0.0",
    title: "Crossover",
    total: "Strategy by Deepansh Rao",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 36,
    rating: "0.0",
    title: "CCI BOLY EMA",
    total: "Strategy by Divya Prakash Dash",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 37,
    rating: "0.0",
    title: "Best Strategy",
    total: "Strategy by Saroj Karki Karki",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 38,
    rating: "0.0",
    title: "Bar RSI",
    total: "Strategy by yograjsinh Vadher",
    img: "/market-menu-images/market-sub-menu-images/TheRightDestanation.svg",
  },
  {
    id: 39,
    rating: "0.0",
    title: "AlaaA",
    total: "Strategy by Saber Al-Husseini",
    img: "/market-menu-images/market-sub-menu-images/WMASquad.svg",
  },
  {
    id: 40,
    rating: "0.0",
    title: "AeroMan",
    total: "Strategy by Mohammad Abdollahi Abdollahi",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 41,
    rating: "0.0",
    title: "ACI",
    total: "Strategy by Taran S",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 42,
    rating: "5.0",
    title: "Trade up",
    total: "Strategy by Haytam Mekkati",
    img: "/market-menu-images/market-sub-menu-images/WMASquad.svg",
  },
  {
    id: 43,
    rating: "5.0",
    title: "Kind Martin",
    total: "Strategy by Shakib Khan",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 44,
    rating: "5.0",
    title: "EMPIREStrategy",
    total: "Strategy by Mohamed Mohamed",
    img: "/market-menu-images/market-sub-menu-images/CandleProbability.svg",
  },
  {
    id: 45,
    rating: "4.0",
    title: "POWER OF EMA",
    total: "Strategy by Jayesh tharesha Tharesha",
    img: "/market-menu-images/market-sub-menu-images/VitorTaki.svg",
  },
  {
    id: 46,
    rating: "3.8",
    title: "Zer0",
    total: "Strategy by mahmoud Madi",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 47,
    rating: "3.8",
    title: "Strategy",
    total: "Strategy by G SUMIT SUMIT",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 48,
    rating: "3.8",
    title: "SAMNIK",
    total: "Strategy by SALWAN KHAN",
    img: "/market-menu-images/market-sub-menu-images/AK2.svg",
  },
  {
    id: 49,
    rating: "3.8",
    title: "Liner Standard",
    total: "Strategy by Night Hawk",
    img: "/market-menu-images/market-sub-menu-images/LinerStandard.svg",
  },
  {
    id: 50,
    rating: "3.8",
    title: "EurovsDolar",
    total: "Strategy by XAT3LMAG8C",
    img: "/market-menu-images/market-sub-menu-images/VitorTaki.svg",
  },
];
