import { Modal } from 'antd';
import './settingsProfile.scss'
import { useAppSelector } from '@store/hooks';
import use2FAQR from 'api/user/use2FAQR';
import use2FAVerify from 'api/user/use2FAVerify';
import { useEffect, useState } from 'react';
import { useCookies } from 'react-cookie';

const TwoFA = () => {
    const [show, setShow] = useState(false);
    const [qrCode, setQRcode] = useState('');
    const [enabled, setEnabled] = useState(false);
    const [otp, setOTP] = useState('');
    const { user } = useAppSelector((state) => state.user);
    const [cookies] = useCookies(["access_token"]);

    useEffect(() => {
        user?.two_factor_authentication_enabled && setEnabled(user?.two_factor_authentication_enabled);
    }, [user?.two_factor_authentication_enabled])

    const { mutate } = use2FAQR({
        onSuccess: (data: { qrcode: string }) => {
            const qr = data.qrcode.startsWith('data:image/png;base64,') ? data.qrcode : 'data:image/png;base64,' + data.qrcode
            setQRcode(qr);
        },
        onError: (error) => { },
    });
    const { mutate: mutateVerify } = use2FAVerify({
        onSuccess: (data) => {
            setEnabled(true);
        },
        onError: (error) => { },
    });

    return (
        <>
            {!enabled ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                    <p>Use one-time passwords generated by an external app to log in. This will help protect your account from hackers.</p>
                    <button
                        onClick={() => {
                            mutate(cookies.access_token);
                        }}
                        className="verifyEmailButton"
                    >
                        Generate QR Code
                    </button>
                </div>
            )
                :
                (
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
                        <p>✔️ Two factor Authentication enabled.</p>
                        <button
                            onClick={() => {

                            }}
                            className="verifyEmailButton"
                        >
                            Re-Generate QR Code
                        </button>
                    </div>
                )}
            <Modal
                rootClassName='settingProfileModal'
                open={qrCode ? true : false}
                onOk={() => setQRcode('')}
                onCancel={() => setQRcode('')}
                footer={null}
                maskClosable={false}
                centered
            >
                <div className='confirmEmailContainer'>
                    <span className='confirmEmailTitle'>Two-factor Authentication</span>
                    <span className='confirmEmailSubTitle'>Use one-time passwords generated by an external app to log in. This will help protect your account from hackers.</span>

                    <div className='confirmEmailInputCotainer' style={{ height: 'max-content' }}>
                        <img src={qrCode} style={{ width: '15vw', maxWidth: 150, height: '15vw' , maxHeight: 150, alignSelf: 'center' }}
                            />

                        <span className='confirmEmailInputlabel' style={{ marginTop: 16 }}>Verify OTP</span>
                        <input className='confirmEmailInput' onChange={(e) => setOTP(e.target.value)} value={otp} type='text' placeholder='Enter OTP from authenticator app.' />
                    </div>
                    <button
                        onClick={() => {
                            if (otp.trim()) {
                                setQRcode('');
                                mutateVerify({
                                    token: cookies.access_token,
                                    otp: otp
                                })
                            }
                        }}
                        className="confirmEmailContinueButton"
                    >
                        Submit
                    </button>
                    <button
                        onClick={() => {
                            setQRcode('');
                        }}
                        className="confirmEmailCancelButton"
                    >
                        Cancel
                    </button>
                </div>
            </Modal>
        </>
    )
}

export default TwoFA