import {
  ApeXProtocolFlag,
  ArbitrumFlag,
  AvalancheFlag,
  BahrainiFlag,
  BinanceCoinFlag,
  BitCoinFlag,
  BitcoinCashFlag,
  BritishFlag,
  CardanoFlag,
  CaymanFlag,
  CelestiaFlag,
  ChainLinkFlag,
  CosmosFlag,
  DaiFlag,
  DodgeCoinFlag,
  EnergySwapFlag,
  EthereumClassicFlag,
  EtheriumFlag,
  EuroFlag,
  FileCoinFlag,
  FirstDigitalFlag,
  GibraltarFlag,
  HederaFlag,
  HongKongFlag,
  InjectiveFlag,
  InmutableXFlag,
  InternetComputerFlag,
  JordanianFlag,
  KaspaFlag,
  KuwaitFlag,
  LeoFlag,
  LidoDaoTokenFlag,
  LiteCoinFlag,
  MakerFlag,
  MoneroFlag,
  NearProtocolFlag,
  OKBFlag,
  OmaniFlag,
  PancakeSwapFlag,
  PolkadotFlag,
  PolygonFlag,
  RenderTokenFlag,
  RocketPoolFlag,
  RussianFlag,
  ShibaFlag,
  SolanaFlag,
  StacksFlag,
  StellarFlag,
  SwissFlag,
  TheGraphFlag,
  ToncoinFlag,
  TronFlag,
  USDCoinFlag,
  USDTBSCFlag,
  USDTERFlag,
  UniswapFlag,
  UsdIcon2,
  UsdtIcon,
  VechainFlag,
  WEMIXTkenFlag,
  WrappedBTCFlag,
  WrappedEtherFlag,
  WrappedLiquidFlag,
  XRPFlag,
} from "../../../../../assets/icons";

export interface InitialAccountsListProps {
  id?: number;
  icon?: JSX.Element;
  title?: string;
  amount?: string;
}

export const InitialAccountsList: InitialAccountsListProps[] = [
  {
    id: 1,
    icon: <UsdIcon2 />,
    title: "USD Account",
    amount: "USD 0.00",
  },
  {
    id: 2,
    icon: <UsdtIcon />,
    title: "USDT Account",
    amount: "USDT 0.00",
  },
  {
    id: 3,
    icon: <UsdIcon2 />,
    title: "USD Account 3",
    amount: "USD 0.00",
  },
  {
    id: 4,
    icon: <KuwaitFlag />,
    title: "Kuwaiti dinar",
    amount: "KWD 0.00",
  },
  {
    id: 5,
    icon: <BahrainiFlag />,
    title: "Bahraini dinar",
    amount: "KWD 0.00",
  },
  {
    id: 6,
    icon: <OmaniFlag />,
    title: "Omani rial",
    amount: "KWD 0.00",
  },
  {
    id: 7,
    icon: <JordanianFlag />,
    title: "Jordanian dinar",
    amount: "JOD 0.00",
  },
  {
    id: 8,
    icon: <BritishFlag />,
    title: "British pound",
    amount: "GBP 0.00",
  },
  {
    id: 9,
    icon: <GibraltarFlag />,
    title: "Gibraltar pound",
    amount: "GIP 0.00",
  },
  {
    id: 10,
    icon: <CaymanFlag />,
    title: "Cayman Islands dollar",
    amount: "KYD 0.00",
  },
  {
    id: 11,
    icon: <SwissFlag />,
    title: "Swiss franc",
    amount: "CHF 0.00",
  },
  {
    id: 12,
    icon: <EuroFlag />,
    title: "Euro",
    amount: "EUR 0.00",
  },
  {
    id: 13,
    icon: <RussianFlag />,
    title: "Russian Ruble",
    amount: "RUB 0.00",
  },
  {
    id: 14,
    icon: <HongKongFlag />,
    title: "Hong Kong Dollar",
    amount: "HDK 0.00",
  },
  {
    id: 15,
    icon: <USDTERFlag />,
    title: "USDT (ERC20)",
    amount: "USDT 0.00",
  },
  {
    id: 16,
    icon: <USDTBSCFlag />,
    title: "USDT (BSC BEP-20)",
    amount: "USDT 0.00",
  },
  {
    id: 17,
    icon: <BitCoinFlag />,
    title: "Bitcoin",
    amount: "BTC 0.00",
  },
  {
    id: 18,
    icon: <ShibaFlag />,
    title: "Shiba Inu",
    amount: "SHIB 0.00",
  },
  {
    id: 19,
    icon: <DodgeCoinFlag />,
    title: "Dodge Coin (BSC BEP-20)",
    amount: "DOGE 0.00",
  },
  {
    id: 20,
    icon: <SolanaFlag />,
    title: "Solana",
    amount: "SOL 0.00",
  },
  {
    id: 21,
    icon: <PolygonFlag />,
    title: "Polygon",
    amount: "MATIC 0.00",
  },
  {
    id: 22,
    icon: <BinanceCoinFlag />,
    title: "Binance Coin (BSC BEP-20)",
    amount: "BNB 0.00",
  },
  {
    id: 23,
    icon: <TronFlag />,
    title: "Tron",
    amount: "TRX 0.00",
  },
  {
    id: 24,
    icon: <USDCoinFlag />,
    title: "USD Coin (TRC20)",
    amount: "USDC 0.00",
  },
  {
    id: 25,
    icon: <XRPFlag />,
    title: "XRP",
    amount: "XRP 0.00",
  },
  {
    id: 26,
    icon: <EtheriumFlag />,
    title: "Ethereum",
    amount: "ETH 0.00",
  },
  {
    id: 27,
    icon: <CardanoFlag />,
    title: "Cardano",
    amount: "ADA 0.00",
  },
  {
    id: 28,
    icon: <AvalancheFlag />,
    title: "Avalanche",
    amount: "AVAX 0.00",
  },
  {
    id: 29,
    icon: <ChainLinkFlag />,
    title: "Chainlink ",
    amount: "LINK 0.00",
  },
  {
    id: 30,
    icon: <WrappedLiquidFlag />,
    title: "Wrapped liquid staked Ether 2.0 ",
    amount: "wstETH 0.00",
  },
  {
    id: 31,
    icon: <PolkadotFlag />,
    title: "Polkadot",
    amount: "DOT 0.00",
  },
  {
    id: 32,
    icon: <WrappedEtherFlag />,
    title: "Wrapped Ether",
    amount: "WETH 0.00",
  },
  {
    id: 33,
    icon: <WrappedBTCFlag />,
    title: "Wrapped BTC",
    amount: "WBTC 0.00",
  },
  {
    id: 34,
    icon: <InmutableXFlag />,
    title: "Inmutable X",
    amount: "IMX 0.00",
  },
  {
    id: 35,
    icon: <UniswapFlag />,
    title: "Uniswap",
    amount: "UNI 0.00",
  },
  {
    id: 36,
    icon: <InternetComputerFlag />,
    title: "Internet Computer ",
    amount: "ICP 0.00",
  },
  {
    id: 37,
    icon: <LiteCoinFlag />,
    title: "Litecoin",
    amount: "LTC 0.00",
  },
  {
    id: 38,
    icon: <BitcoinCashFlag />,
    title: "Bitcoin Cash",
    amount: "BHC 0.00",
  },
  {
    id: 39,
    icon: <PancakeSwapFlag />,
    title: "PancakeSwap ",
    amount: "CAKE 0.00",
  },
  {
    id: 40,
    icon: <KaspaFlag />,
    title: "Kaspa",
    amount: "KAS 0.00",
  },
  {
    id: 41,
    icon: <LeoFlag />,
    title: "LEO",
    amount: "LEO 0.00",
  },
  {
    id: 42,
    icon: <DaiFlag />,
    title: "Dai",
    amount: "DAI 0.00",
  },
  {
    id: 43,
    icon: <FileCoinFlag />,
    title: "Filecoin",
    amount: "FIL 0.00",
  },
  {
    id: 44,
    icon: <EthereumClassicFlag />,
    title: "Ethereum Classic",
    amount: "ETC 0.00",
  },
  {
    id: 45,
    icon: <RenderTokenFlag />,
    title: "Render Token",
    amount: "RNDR 0.00",
  },
  {
    id: 46,
    icon: <HederaFlag />,
    title: "Hedera",
    amount: "HBAR 0.00",
  },
  {
    id: 47,
    icon: <CosmosFlag />,
    title: "Cosmos",
    amount: "ATOM 0.00",
  },
  {
    id: 48,
    icon: <OKBFlag />,
    title: "OKB",
    amount: "OKB 0.00",
  },
  {
    id: 49,
    icon: <ToncoinFlag />,
    title: "Toncoin",
    amount: "TON 0.00",
  },
  {
    id: 50,
    icon: <InjectiveFlag />,
    title: "Injective Protocol",
    amount: "INJ 0.00",
  },
  {
    id: 51,
    icon: <VechainFlag />,
    title: "VeChain",
    amount: "VET 0.00",
  },
  {
    id: 52,
    icon: <FirstDigitalFlag />,
    title: "First Digital USD",
    amount: "FDUSD 0.00",
  },
  {
    id: 53,
    icon: <LidoDaoTokenFlag />,
    title: "Lido Dao Token",
    amount: "LDO 0.00",
  },
  {
    id: 54,
    icon: <CelestiaFlag />,
    title: "Celestia",
    amount: "TIA 0.00",
  },
  {
    id: 55,
    icon: <StacksFlag />,
    title: "Stacks",
    amount: "STX 0.00",
  },
  {
    id: 56,
    icon: <ArbitrumFlag />,
    title: "ARBITRUM",
    amount: "ARB 0.00",
  },
  {
    id: 57,
    icon: <StellarFlag />,
    title: "Stellar",
    amount: "XLM 0.00",
  },
  {
    id: 58,
    icon: <MoneroFlag />,
    title: "Monero",
    amount: "XMR 0.00",
  },
  {
    id: 59,
    icon: <EnergySwapFlag />,
    title: "EnergySwap",
    amount: "ENS 0.00",
  },
  {
    id: 60,
    icon: <WEMIXTkenFlag />,
    title: "WEMIX Token",
    amount: "WEMIX 0.00",
  },
  {
    id: 61,
    icon: <TheGraphFlag />,
    title: "The Graph",
    amount: "GRT 0.00",
  },
  {
    id: 62,
    icon: <MakerFlag />,
    title: "Maker",
    amount: "MKR 0.00",
  },
  {
    id: 63,
    icon: <ApeXProtocolFlag />,
    title: "ApeX Protocol",
    amount: "APEX 0.00",
  },
  {
    id: 64,
    icon: <NearProtocolFlag />,
    title: "Near Protocol",
    amount: "NEAR 0.00",
  },
  {
    id: 65,
    icon: <RocketPoolFlag />,
    title: "Rocket Pool ETH",
    amount: "RETH 0.00",
  },
];
