FROM node:18.18.0 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . .

ARG VITE_API_BASE_URL
ARG VITE_SOCKET_BASE_URL

RUN VITE_API_BASE_URL=$VITE_API_BASE_URL \
 VITE_SOCKET_BASE_URL=$VITE_SOCKET_BASE_URL \
 npm run build:dev

FROM nginx:1.21.3 as production-stage
COPY /nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
RUN chgrp -R 0 /usr/share/nginx/html && \
    chmod -R g=u /usr/share/nginx/html
COPY entrypoint.sh /usr/share/nginx/
RUN chmod +x /usr/share/nginx/entrypoint.sh
ENTRYPOINT ["/usr/share/nginx/entrypoint.sh"]
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
