version: "3.8"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - ${SERVER_PORT}:8080
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_SOCKET_BASE_URL=${VITE_SOCKET_BASE_URL}
      - VITE_PUBLIC_SITE_URL=${VITE_PUBLIC_SITE_URL}
      - VITE_BRAND_NAME=${VITE_BRAND_NAME:-Beyvra}
