FROM node:22-bookworm-slim AS build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm ci
COPY . .

ARG VITE_API_BASE_URL
ARG VITE_SOCKET_BASE_URL
ARG VITE_PUBLIC_SITE_URL
ARG VITE_BRAND_NAME=Beyvra
ARG VITE_GEOIP_ENDPOINT
ARG VITE_REALTIME_V2_ENABLED=false
ARG VITE_REALTIME_V2_V1_FALLBACK_ENABLED=true

RUN VITE_API_BASE_URL=$VITE_API_BASE_URL \
 VITE_SOCKET_BASE_URL=$VITE_SOCKET_BASE_URL \
 VITE_PUBLIC_SITE_URL=$VITE_PUBLIC_SITE_URL \
 VITE_BRAND_NAME=$VITE_BRAND_NAME \
 VITE_GEOIP_ENDPOINT=$VITE_GEOIP_ENDPOINT \
 VITE_REALTIME_V2_ENABLED=$VITE_REALTIME_V2_ENABLED \
 VITE_REALTIME_V2_V1_FALLBACK_ENABLED=$VITE_REALTIME_V2_V1_FALLBACK_ENABLED \
 npm run build

FROM nginx:alpine AS production-stage
ARG VCS_REF=unknown
ARG BUILD_VERSION=unreleased
ARG BUILD_DATE=unknown
LABEL org.opencontainers.image.source="https://github.com/appolon1908-hue/trading-frontend" \
      org.opencontainers.image.revision="$VCS_REF" \
      org.opencontainers.image.version="$BUILD_VERSION" \
      org.opencontainers.image.created="$BUILD_DATE"
COPY nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY config.js.template /etc/nginx/templates/config.js.template
ENV NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html
RUN chgrp -R 0 /usr/share/nginx/html && \
    chmod -R g=u /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
