import * as echarts from "echarts";
import { CanonicalCandle } from "../chartTypes";
import { OverlayMarker } from "./types";

export class NewsCalendarMarkerLayer {
  private chart?: echarts.ECharts; private candles: CanonicalCandle[] = []; private markers: OverlayMarker[] = []; private reservedX: number[] = []; private interactionEnabled = true;
  constructor(private readonly onGraphics: (graphics: object[]) => void, private readonly onActivate: (marker: OverlayMarker) => void) {}
  mount(chart: echarts.ECharts) { this.chart = chart; }
  dispose() { this.chart = undefined; }
  setCandles(candles: readonly CanonicalCandle[]) { this.candles = [...candles]; this.render(); }
  setMarkers(markers: readonly OverlayMarker[]) { this.markers = markers.map((item) => ({ ...item })); this.render(); }
  setReservedX(reservedX: readonly number[]) { this.reservedX = [...reservedX]; this.render(); }
  setInteractionEnabled(enabled: boolean) { this.interactionEnabled = enabled; this.render(); }
  render() { if (!this.chart) return; const positioned = this.markers.map((marker) => { const nearest = this.candles.reduce((best, candle) => Math.abs(Date.parse(candle.openTime) - Date.parse(marker.time)) < Math.abs(Date.parse(best.openTime) - Date.parse(marker.time)) ? candle : best, this.candles[0]); if (!nearest) return undefined; const x = Number(this.chart!.convertToPixel({ xAxisIndex: 0 }, nearest.openTime)); return Number.isFinite(x) ? { marker, x } : undefined; }).filter(Boolean) as Array<{ marker: OverlayMarker; x: number }>;
    const visual: Array<{ marker: OverlayMarker; x: number }> = []; for (const item of positioned.sort((a, b) => a.x - b.x || a.marker.id.localeCompare(b.marker.id))) { const previous = visual.at(-1); if (previous && previous.marker.kind === item.marker.kind && Math.abs(previous.x - item.x) < 28) { previous.marker = { ...previous.marker, id: `${previous.marker.kind}-pixel-cluster-${Math.round(previous.x)}`, eventIds: [...previous.marker.eventIds, ...item.marker.eventIds], count: previous.marker.count + item.marker.count, importance: previous.marker.importance === "HIGH" || item.marker.importance === "HIGH" ? "HIGH" : previous.marker.importance === "MEDIUM" || item.marker.importance === "MEDIUM" ? "MEDIUM" : "LOW" }; } else visual.push({ marker: { ...item.marker, eventIds: [...item.marker.eventIds] }, x: item.x }); }
    const graphics = visual.map(({ marker, x }) => { const y = this.reservedX.some((reservedTradeX) => Math.abs(reservedTradeX - x) < 32) ? 104 : 72; const color = marker.importance === "HIGH" ? "#ef4444" : marker.importance === "MEDIUM" ? "#f59e0b" : "#38bdf8"; const label = `${marker.kind === "news" ? "N" : "E"}${marker.count > 1 ? ` ${marker.count}` : ""}`; return { id: marker.id, type: "group", z: 80, silent: !this.interactionEnabled, onclick: () => this.interactionEnabled && this.onActivate(marker), children: [{ type: "circle", shape: { cx: x, cy: y, r: marker.count > 1 ? 13 : 10 }, style: { fill: color, stroke: "#fff", lineWidth: 1 } }, { type: "text", silent: true, x: x - (marker.count > 1 ? 9 : 4), y: y - 6, style: { text: label, fill: "#fff", fontWeight: 700 } }], tooltip: { formatter: `${marker.importance} • ${marker.kind === "news" ? "NEWS" : "ECONOMIC"}<br/>${marker.title}<br/>${new Date(marker.time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", timeZone: "UTC" })} UTC<br/>${marker.source}<br/>View details →` } }; }); this.onGraphics(graphics); }
}
