import { describe, expect, it } from "vitest";
import { NewsCalendarOverlayStore } from "./NewsCalendarOverlayStore";
import { NewsCalendarMarkerLayer } from "./NewsCalendarMarkerLayer";
import { EconomicEvent, NewsArticle } from "./types";

const news = (id: string, patch: Partial<NewsArticle> = {}): NewsArticle => ({ article_id: id, provider_id: "approved-test-provider", provider_article_id: `provider-${id}`, headline: `Headline ${id}`, canonical_url: `https://example.invalid/${id}`, published_at: "2026-08-07T03:15:00Z", importance: "HIGH", affected_instruments: ["BTC-USD"], status: "PUBLISHED", ...patch });
const economic = (id: string, patch: Partial<EconomicEvent> = {}): EconomicEvent => ({ event_id: id, provider_id: "approved-test-provider", title: `Event ${id}`, scheduled_at: "2026-08-07T04:00:00Z", importance: "HIGH", affected_instruments: ["BTC-USD"], status: "SCHEDULED", ...patch });
const envelope = (event_id: string, sequence: number, event_type: string, data: NewsArticle | EconomicEvent) => ({ event_id, event_type, event_version: 1, sequence, occurred_at: "2026-08-07T03:15:00Z", server_time: "2026-08-07T03:15:01Z", source: "approved-test-provider", data });

describe("NewsCalendarOverlayStore", () => {
  it("deduplicates provider articles and canonical URLs", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceNews([news("1"), news("2", { provider_article_id: "provider-1" }), news("3", { canonical_url: "https://example.invalid/1" })]); expect(store.getSnapshot().news).toHaveLength(1); });
  it("updates and retracts one canonical article", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceNews([news("1")]); expect(store.applyRealtime("news.market", envelope("u1", 1, "news.article.updated", news("1", { headline: "Updated", status: "UPDATED" })))).toBe(true); expect(store.getSnapshot().news[0].headline).toBe("Updated"); store.applyRealtime("news.market", envelope("r1", 2, "news.article.retracted", news("1", { status: "RETRACTED" }))); expect(store.getSnapshot().news).toEqual([]); });
  it("updates and cancels economic events", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceEconomic([economic("1")]); store.applyRealtime("economic-calendar", envelope("u1", 1, "economic.event.updated", economic("1", { actual_value: "3.2", status: "UPDATED" }))); expect(store.getSnapshot().economicEvents[0].actual_value).toBe("3.2"); store.applyRealtime("economic-calendar", envelope("c1", 2, "economic.event.cancelled", economic("1", { status: "CANCELLED" }))); expect(store.getSnapshot().economicEvents).toEqual([]); });
  it("rejects duplicate and stale realtime envelopes", () => { const store = new NewsCalendarOverlayStore(); expect(store.applyRealtime("news.market", envelope("one", 2, "news.article.published", news("1")))).toBe(true); expect(store.getSnapshot().latestSequence["news.market"]).toBe(2); expect(store.applyRealtime("news.market", envelope("one", 3, "news.article.published", news("2")))).toBe(false); expect(store.applyRealtime("news.market", envelope("old", 1, "news.article.published", news("2")))).toBe(false); });
  it("filters locally by instrument, importance, and kind without mutating source", () => { const store = new NewsCalendarOverlayStore(); const source = news("1"); const before = structuredClone(source); store.setVisible(true); store.setInstrumentFilter("BTC-USD"); store.replaceNews([source, news("2", { importance: "LOW", affected_instruments: ["ETH-USD"] })]); store.replaceEconomic([economic("1")]); store.setFilter("high"); expect(store.markersFor()).toHaveLength(2); expect(store.getSnapshot().importanceFilter).toBe("HIGH"); store.setFilter("news"); expect(store.markersFor().every((item) => item.kind === "news")).toBe(true); expect(source).toEqual(before); });
  it("fail-closed state removes stale provider content", () => { const store = new NewsCalendarOverlayStore(); store.replaceNews([news("1")]); store.setUnavailable(); expect(store.getSnapshot().news).toEqual([]); expect(store.getSnapshot().providerState).toBe("unavailable"); });
  it("clusters same-kind events in the same minute without duplicates", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.setInstrumentFilter("BTC-USD"); store.replaceNews([news("1"), news("2", { published_at: "2026-08-07T03:15:40Z" })]); const markers = store.markersFor(); expect(markers).toHaveLength(1); expect(markers[0].count).toBe(2); expect(markers[0].eventIds).toEqual(["1", "2"]); });
  it("owns drawer selection independently from overlay visibility", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.setInstrumentFilter("BTC-USD"); store.replaceNews([news("1")]); const marker = store.markersFor()[0]; store.selectMarker(marker); expect(store.getSnapshot()).toMatchObject({ drawerOpen: true, selectedEventId: "1", selectedEventType: "NEWS", visibility: true }); store.closeDrawer(); expect(store.getSnapshot()).toMatchObject({ drawerOpen: false, visibility: true }); expect(store.markersFor()).toHaveLength(1); });
  it("renders a compact activatable marker without article content", () => { let graphics: Array<Record<string, unknown>> = []; let activated = ""; const layer = new NewsCalendarMarkerLayer((next) => { graphics = next as Array<Record<string, unknown>>; }, (marker) => { activated = marker.id; }); const article = news("1", { summary: "Licensed summary that belongs only in the drawer" }); const marker = { id: "news-1", kind: "news" as const, eventIds: ["1"], count: 1, time: article.published_at, importance: article.importance, title: article.headline, source: article.provider_id, instrumentIds: article.affected_instruments }; layer.mount({ convertToPixel: () => 100 } as never); layer.setCandles([{ openTime: article.published_at, closeTime: "2026-08-07T03:16:00Z", open: "1", high: "2", low: "0.5", close: "1.5", volume: "1", complete: true, sequence: 1 }]); layer.setMarkers([marker]); expect(graphics).toHaveLength(1); expect(JSON.stringify(graphics[0])).not.toContain(article.summary); (graphics[0].onclick as () => void)(); expect(activated).toBe("news-1"); });
  it("normalizes compact provider events without exposing payload authority", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.setInstrumentFilter("BTC-USD"); expect(store.applyRealtime("news.instrument:BTC-USD", { event_id: "compact-1", event_type: "news.article.published", event_version: 1, sequence: 1, occurred_at: "2026-08-07T03:15:00Z", server_time: "2026-08-07T03:15:01Z", source: "approved-provider", data: { article_id: "compact", headline: "Compact headline", importance: "HIGH" } })).toBe(true); expect(store.markersFor()[0]).toMatchObject({ title: "Compact headline", instrumentIds: ["BTC-USD"] }); });
  it("clusters by rendered pixel and yields the trade collision lane", () => { let graphics: Array<Record<string, any>> = []; let activated: string[] = []; const layer = new NewsCalendarMarkerLayer((next) => { graphics = next as Array<Record<string, any>>; }, (marker) => { activated = marker.eventIds; }); layer.mount({ convertToPixel: () => 100 } as never); layer.setCandles([{ openTime: "2026-08-07T03:15:00Z", closeTime: "2026-08-07T03:16:00Z", open: "1", high: "2", low: "0.5", close: "1.5", volume: "1", complete: true, sequence: 1 }]); const marker = (id: string) => ({ id: `news-${id}`, kind: "news" as const, eventIds: [id], count: 1, time: "2026-08-07T03:15:00Z", importance: "HIGH" as const, title: `Headline ${id}`, source: "approved", instrumentIds: ["BTC-USD"] }); layer.setMarkers([marker("1"), marker("2")]); layer.setReservedX([101]); expect(graphics).toHaveLength(1); expect(graphics[0].children[0].shape.cy).toBe(104); (graphics[0].onclick as () => void)(); expect(activated).toEqual(["1", "2"]); });
  it("bounds loaded projections during endurance-style realtime churn", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.setInstrumentFilter("BTC-USD"); for (let index = 1; index <= 1_100; index += 1) store.applyRealtime("news.instrument:BTC-USD", envelope(`bounded-${index}`, index, "news.article.published", news(String(index), { published_at: new Date(1_786_076_100_000 + index * 60_000).toISOString() }))); expect(store.getSnapshot().news).toHaveLength(1_000); expect(store.markersFor().length).toBeLessThanOrEqual(1_000); });
});
