import { EconomicEvent, NewsArticle, OverlayEventType, OverlayFilter, OverlayMarker, OverlaySnapshot } from "./types";
import { readWithLegacyMigration, writeCompatibilityValue } from "compat/storageKeys";

type FilterStorage = Pick<Storage, "getItem" | "setItem">; const FILTER_KEY = "beyvra.chart.event-filter.v1"; const LEGACY_FILTER_KEY = "codestra.chart.event-filter.v1"; const allowedFilters = new Set<OverlayFilter>(["all", "trades", "high", "news", "economic"]);
const initial = (storage?: FilterStorage): OverlaySnapshot => { let filter: OverlayFilter = "all"; try { const saved = readWithLegacyMigration(storage, FILTER_KEY, LEGACY_FILTER_KEY); if (allowedFilters.has(saved as OverlayFilter)) filter = saved as OverlayFilter; } catch { /* invalid preference is isolated */ } return { news: [], economicEvents: [], drawerOpen: false, filter, visibility: false, importanceFilter: filter === "high" ? "HIGH" : "ALL", instrumentFilter: "", latestSequence: {}, providerState: "idle", revision: 0 }; };
export class NewsCalendarOverlayStore {
  private state: OverlaySnapshot; private listeners = new Set<() => void>(); private seenEventIds = new Set<string>(); private seenEventOrder: string[] = []; private sequences = new Map<string, number>();
  constructor(private readonly storage: FilterStorage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) { this.state = initial(storage); }
  subscribe = (listener: () => void) => { this.listeners.add(listener); return () => this.listeners.delete(listener); };
  getSnapshot = () => this.state;
  private emit(patch: Partial<OverlaySnapshot>) { this.state = { ...this.state, ...patch, revision: this.state.revision + 1 }; this.listeners.forEach((listener) => listener()); }
  setVisible(visibility: boolean) { this.emit({ visibility }); }
  openDrawer(selectedEventId?: string, selectedEventType?: OverlayEventType) { this.emit({ drawerOpen: true, selectedEventId, selectedEventType }); }
  closeDrawer() { this.emit({ drawerOpen: false, selectedEventId: undefined, selectedEventType: undefined }); }
  selectMarker(marker: OverlayMarker) { this.openDrawer(marker.eventIds[0], marker.kind === "news" ? "NEWS" : "ECONOMIC_EVENT"); }
  setInstrumentFilter(instrumentFilter: string) { if (instrumentFilter !== this.state.instrumentFilter) this.emit({ instrumentFilter }); }
  setLoading() { this.emit({ providerState: "loading" }); }
  setUnavailable() { this.emit({ providerState: "unavailable", news: [], economicEvents: [] }); }
  setFilter(filter: OverlayFilter) { if (!allowedFilters.has(filter)) return; this.emit({ filter, importanceFilter: filter === "high" ? "HIGH" : "ALL" }); try { writeCompatibilityValue(this.storage, FILTER_KEY, filter); } catch { /* preference failure is non-fatal */ } }
  replaceNews(news: readonly NewsArticle[]) { this.emit({ news: this.dedupeNews(news).slice(0, 1_000), providerState: "available" }); }
  mergeNewsDetail(article: NewsArticle) { this.emit({ news: this.dedupeNews([article, ...this.state.news.filter((item) => item.article_id !== article.article_id)]), providerState: "available" }); }
  replaceEconomic(events: readonly EconomicEvent[]) { this.emit({ economicEvents: this.dedupeEconomic(events).slice(0, 1_000), providerState: "available" }); }
  applyRealtime(channel: string, event: Record<string, unknown>): boolean {
    const eventId = String(event.event_id || ""); const sequence = Number(event.sequence); const type = String(event.event_type || "");
    if (!type.startsWith("news.article.") && !type.startsWith("economic.event.")) return false;
    if (!eventId || Number(event.event_version) < 1 || !event.occurred_at || !event.server_time || !event.source || !Number.isFinite(sequence) || this.seenEventIds.has(eventId)) return false;
    if (sequence <= (this.sequences.get(channel) ?? -1)) return false;
    const data = (event.data || {}) as Record<string, unknown>; let apply: (() => void) | undefined;
    if (type.startsWith("news.article.")) {
      const articleId = String(data.article_id || ""); if (!articleId) return false; const existing = this.state.news.find((item) => item.article_id === articleId); const instrument = channel.startsWith("news.instrument:") ? channel.slice("news.instrument:".length) : undefined;
      const article: NewsArticle = { ...existing, article_id: articleId, provider_id: String(data.provider_id || existing?.provider_id || event.source), provider_article_id: String(data.provider_article_id || existing?.provider_article_id || articleId), headline: String(data.headline || existing?.headline || "News update"), summary: data.summary === undefined ? existing?.summary : String(data.summary), publisher: data.publisher === undefined ? existing?.publisher : String(data.publisher), canonical_url: data.canonical_url === undefined ? existing?.canonical_url : data.canonical_url ? String(data.canonical_url) : null, published_at: String(data.published_at || existing?.published_at || event.occurred_at), updated_at: data.updated_at === undefined ? existing?.updated_at : data.updated_at ? String(data.updated_at) : null, retracted_at: data.retracted_at === undefined ? existing?.retracted_at : data.retracted_at ? String(data.retracted_at) : null, importance: (["LOW", "MEDIUM", "HIGH"].includes(String(data.importance)) ? data.importance : existing?.importance || "MEDIUM") as NewsArticle["importance"], affected_instruments: Array.isArray(data.affected_instruments) ? data.affected_instruments.map(String) : existing?.affected_instruments || (instrument ? [instrument] : []), status: (type.endsWith("retracted") ? "RETRACTED" : type.endsWith("updated") ? "UPDATED" : "PUBLISHED") };
      apply = () => { const current = this.state.news.filter((item) => item.article_id !== articleId); this.replaceNews(type.endsWith("retracted") ? current : [article, ...current]); };
    } else {
      const calendarId = String(data.event_id || ""); if (!calendarId) return false; const existing = this.state.economicEvents.find((item) => item.event_id === calendarId);
      const item: EconomicEvent = { ...existing, event_id: calendarId, provider_id: String(data.provider_id || existing?.provider_id || event.source), title: String(data.title || existing?.title || "Economic event update"), country: data.country === undefined ? existing?.country : String(data.country), currency: data.currency === undefined ? existing?.currency : String(data.currency), scheduled_at: String(data.scheduled_at || existing?.scheduled_at || event.occurred_at), actual_at: data.actual_at === undefined ? existing?.actual_at : data.actual_at ? String(data.actual_at) : null, previous_value: data.previous_value === undefined ? existing?.previous_value : String(data.previous_value), forecast_value: data.forecast_value === undefined ? existing?.forecast_value : String(data.forecast_value), actual_value: data.actual_value === undefined ? existing?.actual_value : String(data.actual_value), unit: data.unit === undefined ? existing?.unit : String(data.unit), importance: (["LOW", "MEDIUM", "HIGH"].includes(String(data.importance)) ? data.importance : existing?.importance || "MEDIUM") as EconomicEvent["importance"], affected_instruments: Array.isArray(data.affected_instruments) ? data.affected_instruments.map(String) : existing?.affected_instruments || [], status: (type.endsWith("cancelled") ? "CANCELLED" : type.endsWith("updated") ? "UPDATED" : existing?.status || "SCHEDULED") };
      apply = () => { const current = this.state.economicEvents.filter((eventItem) => eventItem.event_id !== calendarId); this.replaceEconomic(type.endsWith("cancelled") ? current : [item, ...current]); };
    }
    this.seenEventIds.add(eventId); this.seenEventOrder.push(eventId); if (this.seenEventOrder.length > 10_000) this.seenEventIds.delete(this.seenEventOrder.shift()!); this.sequences.set(channel, sequence); this.state = { ...this.state, latestSequence: { ...this.state.latestSequence, [channel]: sequence } }; apply(); return true;
  }
  markersFor(instrumentId = this.state.instrumentFilter): OverlayMarker[] {
    if (!this.state.visibility || !instrumentId) return []; const high = this.state.importanceFilter === "HIGH"; const allowNews = ["all", "high", "news"].includes(this.state.filter); const allowEconomic = ["all", "high", "economic"].includes(this.state.filter);
    const news = allowNews ? this.state.news.filter((item) => item.affected_instruments.includes(instrumentId) && (!high || item.importance === "HIGH")).map((item): OverlayMarker => ({ id: `news-${item.article_id}`, kind: "news", eventIds: [item.article_id], count: 1, time: item.published_at, importance: item.importance, title: item.headline, source: item.publisher || item.provider_id, instrumentIds: item.affected_instruments })) : [];
    const economic = allowEconomic ? this.state.economicEvents.filter((item) => item.affected_instruments.includes(instrumentId) && (!high || item.importance === "HIGH") && item.status !== "CANCELLED").map((item): OverlayMarker => ({ id: `economic-${item.event_id}`, kind: "economic", eventIds: [item.event_id], count: 1, time: item.scheduled_at, importance: item.importance, title: item.title, source: item.provider_id, instrumentIds: item.affected_instruments })) : [];
    return this.cluster([...news, ...economic]);
  }
  eventsForSelection() { const marker = this.markersFor().find((item) => item.eventIds.includes(this.state.selectedEventId || "")); if (!marker) return []; return marker.kind === "news" ? this.state.news.filter((item) => marker.eventIds.includes(item.article_id)) : this.state.economicEvents.filter((item) => marker.eventIds.includes(item.event_id)); }
  private cluster(markers: OverlayMarker[]) { const clusters = new Map<string, OverlayMarker>(); for (const marker of markers) { const minute = Math.floor(Date.parse(marker.time) / 60_000); const key = `${marker.kind}:${minute}`; const current = clusters.get(key); if (!current) { clusters.set(key, marker); continue; } const importance = current.importance === "HIGH" || marker.importance === "HIGH" ? "HIGH" : current.importance === "MEDIUM" || marker.importance === "MEDIUM" ? "MEDIUM" : "LOW"; clusters.set(key, { ...current, id: `${current.kind}-cluster-${minute}`, eventIds: [...current.eventIds, ...marker.eventIds], count: current.count + marker.count, importance }); } return [...clusters.values()].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)); }
  private dedupeNews(items: readonly NewsArticle[]) { const provider = new Set<string>(); const urls = new Set<string>(); return items.filter((item) => { const key = `${item.provider_id}:${item.provider_article_id}`; if (!item.article_id || !item.headline || !item.published_at || provider.has(key) || (item.canonical_url && urls.has(item.canonical_url))) return false; provider.add(key); if (item.canonical_url) urls.add(item.canonical_url); return item.status !== "RETRACTED"; }).map((item) => ({ ...item, affected_instruments: Array.isArray(item.affected_instruments) ? [...item.affected_instruments] : [] })); }
  private dedupeEconomic(items: readonly EconomicEvent[]) { const ids = new Set<string>(); return items.filter((item) => item.event_id && item.title && item.scheduled_at && !ids.has(item.event_id) && (ids.add(item.event_id) || true)).map((item) => ({ ...item, affected_instruments: Array.isArray(item.affected_instruments) ? [...item.affected_instruments] : [] })); }
}
