import { describe, expect, it } from "vitest";
import { NewsCalendarOverlayStore } from "./NewsCalendarOverlayStore";
import { EconomicEvent, NewsArticle } from "./types";

const news = (id: string, patch: Partial<NewsArticle> = {}): NewsArticle => ({ article_id: id, provider_id: "approved-test-provider", provider_article_id: `provider-${id}`, headline: `Headline ${id}`, canonical_url: `https://example.invalid/${id}`, published_at: "2026-08-07T03:15:00Z", importance: "HIGH", affected_instruments: ["BTC-USD"], status: "PUBLISHED", ...patch });
const economic = (id: string, patch: Partial<EconomicEvent> = {}): EconomicEvent => ({ event_id: id, provider_id: "approved-test-provider", title: `Event ${id}`, scheduled_at: "2026-08-07T04:00:00Z", importance: "HIGH", affected_instruments: ["BTC-USD"], status: "SCHEDULED", ...patch });

describe("NewsCalendarOverlayStore", () => {
  it("deduplicates provider articles and canonical URLs", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceNews([news("1"), news("2", { provider_article_id: "provider-1" }), news("3", { canonical_url: "https://example.invalid/1" })]); expect(store.getSnapshot().news).toHaveLength(1); });
  it("updates and retracts one canonical article", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceNews([news("1")]); expect(store.applyRealtime("news.market", { event_id: "u1", sequence: 1, event_type: "news.article.updated", data: news("1", { headline: "Updated", status: "UPDATED" }) })).toBe(true); expect(store.getSnapshot().news[0].headline).toBe("Updated"); store.applyRealtime("news.market", { event_id: "r1", sequence: 2, event_type: "news.article.retracted", data: news("1", { status: "RETRACTED" }) }); expect(store.getSnapshot().news).toEqual([]); });
  it("updates and cancels economic events", () => { const store = new NewsCalendarOverlayStore(); store.setVisible(true); store.replaceEconomic([economic("1")]); store.applyRealtime("economic-calendar", { event_id: "u1", sequence: 1, event_type: "economic.event.updated", data: economic("1", { actual_value: "3.2", status: "UPDATED" }) }); expect(store.getSnapshot().economicEvents[0].actual_value).toBe("3.2"); store.applyRealtime("economic-calendar", { event_id: "c1", sequence: 2, event_type: "economic.event.cancelled", data: economic("1", { status: "CANCELLED" }) }); expect(store.getSnapshot().economicEvents).toEqual([]); });
  it("rejects duplicate and stale realtime envelopes", () => { const store = new NewsCalendarOverlayStore(); expect(store.applyRealtime("news.market", { event_id: "one", sequence: 2, event_type: "news.article.published", data: news("1") })).toBe(true); expect(store.applyRealtime("news.market", { event_id: "one", sequence: 3, event_type: "news.article.published", data: news("2") })).toBe(false); expect(store.applyRealtime("news.market", { event_id: "old", sequence: 1, event_type: "news.article.published", data: news("2") })).toBe(false); });
  it("filters locally by instrument, importance, and kind without mutating source", () => { const store = new NewsCalendarOverlayStore(); const source = news("1"); const before = structuredClone(source); store.setVisible(true); store.replaceNews([source, news("2", { importance: "LOW", affected_instruments: ["ETH-USD"] })]); store.replaceEconomic([economic("1")]); store.setFilter("high"); expect(store.markersFor("BTC-USD")).toHaveLength(2); store.setFilter("news"); expect(store.markersFor("BTC-USD").every((item) => item.kind === "news")).toBe(true); expect(source).toEqual(before); });
  it("fail-closed state removes stale provider content", () => { const store = new NewsCalendarOverlayStore(); store.replaceNews([news("1")]); store.setUnavailable(); expect(store.getSnapshot().news).toEqual([]); expect(store.getSnapshot().providerState).toBe("unavailable"); });
});
